# Generated by Django 4.0.3 on 2023-01-09 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0004_watchlist_platform'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='watchlist',
            name='genre',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='genre', to='watchlist_app.moviegenre'),
            preserve_default=False,
        ),
    ]
